# .goreleaser.yml

builds:
  # You can have multiple builds defined as a yaml list
  -
    id: "Ark-cli"
    dir: go

    env:
      - CGO_ENABLED=0

    goos:
      - freebsd
      - windows
      - linux

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64
      - arm64

    # GOMIPS and GOMIPS64 to build when GOARCH is mips, mips64, mipsle or mips64le.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Default is empty.
    gomips:
      - hardfloat
      - softfloat


archives:
  -

    # Builds reference which build instances should be archived in this archive.
    builds:
      - default

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux


    wrap_in_directory: true

    format: zip

    format_overrides:
      - goos: windows
        format: zip

    files:
      - none*