# .goreleaser.yml

builds:
  # You can have multiple builds defined as a yaml list
  -
    id: "Ark-cli"

    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - windows



archives:
  -

    # Builds reference which build instances should be archived in this archive.
    builds:
      - default

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS

    files:
      - none*